docker:
  image: g4s8/rultor:alpine3.10
architect:
  - dgroup

readers:
  - "urn:github:1651114"

assets:
  settings.xml: "dgroup/home#settings.xml"
  pubring.gpg:  "dgroup/home#8DF36117-arch4u-pmd_pubring.gpg"
  secring.gpg:  "dgroup/home#8DF36117-arch4u-pmd_secring.gpg"

merge:
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - mvn -Pqulice clean package

release:
  sensitive:
    - settings.xml
    - pubring.gpg
    - secring.gpg
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git add pom.xml
    git commit -am "${tag}"
    mvn -X -V -Dgpg.homedir="$HOME" -P qulice,ossrh-arch4u -s ../settings.xml clean deploy
