name: Post changelog
on:
  release:
    types: [published]

jobs:
  post-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Send changelog to telegram channel
        uses: tyagdit/release-telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          channel: ${{ secrets.TELEGRAM_CHAT }}
          changelog: ${{ github.event.release.body }}