name: Telegram

# triggers for notifying
#  these are some important trigger cases could be change as need
# check here https://developer.github.com/webhooks/
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: [created]
  push:

jobs:
  build:
    name: Telegram Notification
    runs-on: ubuntu-latest
    steps:
      - name: Notify channel
        uses: athul/statusoli@master
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          status: ${{ job.status }}